javascript:
  - changed-files:
      - any-glob-to-any-file: "**/*.js"

ui/ux:
  - changed-files:
      - any-glob-to-any-file:
          - "app/**"
          - "assets/**"

documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"
